package global.phaser.types.sound;

/**
	Audio sprite sound type.
**/
typedef AudioSpriteSound = {
	/**
		Local reference to 'spritemap' object form json file generated by audiosprite tool.
	**/
	var spritemap : Dynamic;
};